'use strict';

module.exports = {
  badCertificate: "BadCertificate",
  badCertificateEnvironment: "BadCertificateEnvironment",
  badDeviceToken: "BadDeviceToken",
  badExpirationDate: "BadExpirationDate",
  badMessageId: "BadMessageId",
  badPath: "BadPath",
  badPriority: "BadPriority",
  badTopic: "BadTopic",
  deviceTokenNotForTopic: "DeviceTokenNotForTopic",
  duplicateHeaders: "DuplicateHeaders",
  expiredProviderToken: "ExpiredProviderToken",
  forbidden: "Forbidden",
  idleTimeout: "IdleTimeout",
  internalServerError: "InternalServerError",
  invalidProviderToken: "InvalidProviderToken",
  methodNotAllowed: "MethodNotAllowed",
  missingDeviceToken: "MissingDeviceToken",
  missingTopic: "MissingTopic",
  payloadEmpty: "PayloadEmpty",
  payloadTooLarge: "PayloadTooLarge",
  serviceUnavailable: "ServiceUnavailable",
  shutdown: "Shutdown",
  tooManyRequests: "TooManyRequests",
  topicDisallowed: "TopicDisallowed",
  unknownError: "UnknownError",
  unregistered: "Unregistered"
};
