name: Security Code Scan
on:
  pull_request:
    branches:
      - develop
      - master
      - main
      - staging

jobs:
  bearer:
    runs-on: ubuntu-latest
    steps:
      # Need to checkout current repo first
      - uses: actions/checkout@v3
        name: Checkout current repo
        with:
          repository: ${{ github.repository }}
      # Do the magic: checkout action repo
      - uses: actions/checkout@v3
        name: Checkout action repo
        with:
          repository: AskTia/devops
          ref: main
          token: ${{ secrets.TIA_GITHUB_PAT }}
          path: .github/actions
      #this checks out the bearer repo
      - uses: ./.github/actions/bearer/lib
        name: Run the bearer action
        id: bearer
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      #check back out
      - uses: actions/checkout@v3
        name: Re-check out actions repo
        with:
          repository: AskTia/devops
          ref: main
          token: ${{ secrets.TIA_GITHUB_PAT }}
          path: .github/actions
